feat(sources): add git option

diff --git a/edeb b/edeb
--- a/edeb
+++ b/edeb
@@ -106,6 +106,27 @@ build_deb() {
     popd >/dev/null || exit 1 
   }
 
+  git-add() {
+    pushd "$(dirname ${edeb})" >/dev/null || exit 1
+    log debug "Fetch[Git] $*"
+
+    [ -z "$2" ] && log error "Missing repo path for $1." && exit 1
+
+    if [ -d "$srcdir/$2" ]; then
+      log debug "Updating $1..."
+    
+      pushd "$srcdir/$2" >/dev/null || exit 1
+        git pull
+      popd >/dev/null || exit 1 
+    else
+      log debug "Cloning $1..."
+      git clone "$1" "$srcdir/$2"
+    fi
+
+    popd >/dev/null || exit 1 
+
+  }
+
   sources
 
   log info "Running prepare()"
